/* Write your T-SQL query statement below */
SELECT V.CUSTOMER_ID as customer_id , COUNT(V.VISIT_ID) as count_no_trans
FROM VISITS V LEFT OUTER JOIN TRANSACTIONS T
ON V.VISIT_ID = T.VISIT_ID 
WHERE T.TRANSACTION_ID IS NULL
GROUP BY V.CUSTOMER_ID